# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-17 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_samplereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='have_review',
            field=models.BooleanField(default=False),
        ),
    ]
