# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-18 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_order_coupon_price'),
        ('sample', '0003_sample_have_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Coupon'),
        ),
    ]
