# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
