# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
