# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20160508_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='desc',
        ),
    ]
