# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20160511_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointhistory',
            name='record',
            field=models.IntegerField(default=0),
        ),
    ]
