# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
        ('item', '0010_auto_20160508_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ingredients',
            field=models.ManyToManyField(to='ingredient.Ingredient'),
        ),
    ]
