# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_item_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='ingredients',
            field=models.ManyToManyField(blank=True, null=True, to='ingredient.Ingredient'),
        ),
    ]
