# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
        ('item', '0013_auto_20160514_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemIngredientCombination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingredient.Ingredient')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='item',
            name='ingredients',
            field=models.ManyToManyField(blank=True, through='item.ItemIngredientCombination', to='ingredient.Ingredient'),
        ),
        migrations.AddField(
            model_name='itemingredientcombination',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.Item'),
        ),
    ]
