# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_auto_20160514_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='main1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='main2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='main3',
            field=models.BooleanField(default=False),
        ),
    ]
