# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-16 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_auto_20160908_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
    ]
