# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-12 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0017_item_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_order',
            field=models.IntegerField(default=0),
        ),
    ]
