# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 01:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 26, 1, 58, 3, 895401, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 26, 1, 58, 8, 191306, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
