# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 02:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20160426_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 26, 11, 18, 11, 485239)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 26, 11, 18, 11, 486266)),
        ),
    ]
