# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20160426_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
