# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20160426_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
