# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20160426_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_tracking_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
