# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20160514_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_id', models.CharField(max_length=50, unique=True)),
                ('kind_of', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(default=0)),
                ('used', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
