# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_coupon_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='subject',
            field=models.CharField(default='', max_length=50),
        ),
    ]
