# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_coupon_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='condition',
            field=models.IntegerField(default=0),
        ),
    ]
