# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-13 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_coupon_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_price',
            field=models.IntegerField(default=0),
        ),
    ]
