# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kcia_no', models.IntegerField(unique=True)),
                ('ko_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('en_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('ewg_high_grade', models.IntegerField(default=-1)),
                ('ewg_low_grade', models.IntegerField(default=-1)),
                ('caution20', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
