# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
